name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        ...
    - name: Commit files
      run: |
        git commit -m "Add changes" -a
    - name: Push changes
    - uses: ad-m/github-push-action@master 
      env:
        INPUT_REPOSITORY: rosran/trackerRepo 
        INPUT_FORCE: true 
        INPUT_TAGS: true 
        INPUT_ACTOR: rosran
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}       
    
        
