name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Commit files
      run: |
        git status
        git push origin HEAD:master --follow-tags --force --tags
        mkdir repo1
        ll
        
